name: learn-github-actions

on: [push] # The action will be triggered on every push

jobs: 
  run-tests: 
    runs-on: ubuntu-latest # The action will run on an ubuntu server
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4  # With this action the server will get the current code of the repo

      - name: Setup node 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: run tests
        run: |
          npm i
          npm run test
