name: build dockerfile

on: 
  push:

jobs: 
  build-image:
    uses: organization/example-repo/.github/workflows/called_workflow.yml@main
    secrets: inherit
    with: 
      dockerfile-path: docker/Dockerfile
      